[[MKL]]
arch = "x86_64"
git-tree-sha1 = "a41f069dc4a8aaa85efd4ee17b00686f2fdf2bd5"
lazy = true
libc = "glibc"
os = "linux"

    [[MKL.download]]
    sha256 = "43273e67bde105747b1f35f774d631ef1dbd21bdffcd0c335290bb6cfbd2efac"
    url = "https://github.com/JuliaBinaryWrappers/MKL_jll.jl/releases/download/MKL-v2025.0.1+0/MKL.v2025.0.1.x86_64-linux-gnu.tar.gz"
[[MKL]]
arch = "x86_64"
git-tree-sha1 = "b4be4a930ca1e5fa6ec9e96c45b7420bf1a0b40c"
lazy = true
os = "windows"

    [[MKL.download]]
    sha256 = "ca3d055c1eb4842586fd20447da95242d4de7b2f709d37a398d6a5ae42ae014e"
    url = "https://github.com/JuliaBinaryWrappers/MKL_jll.jl/releases/download/MKL-v2025.0.1+0/MKL.v2025.0.1.x86_64-w64-mingw32.tar.gz"
